package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DefectComponent generated by hbm2java
 */
@Entity
@Table(name = "DEFECT_COMPONENT", schema = "QACUBE_IMPORT_STAGE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DEFECT_ID", "COMPONENT_ID" }))
public class DefectComponent implements java.io.Serializable {

	private DefectComponentId id;
	private Defect defect;

	public DefectComponent() {
	}

	public DefectComponent(DefectComponentId id, Defect defect) {
		this.id = id;
		this.defect = defect;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "defectId", column = @Column(name = "DEFECT_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "componentId", column = @Column(name = "COMPONENT_ID", nullable = false, precision = 38, scale = 0)) })
	public DefectComponentId getId() {
		return this.id;
	}

	public void setId(DefectComponentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEFECT_ID", nullable = false, insertable = false, updatable = false)
	public Defect getDefect() {
		return this.defect;
	}

	public void setDefect(Defect defect) {
		this.defect = defect;
	}

}
