package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExecutionList generated by hbm2java
 */
@Entity
@Table(name = "EXECUTION_LIST", schema = "QACUBE_IMPORT_STAGE")
public class ExecutionList implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String sourceOrder;
	private String folderName;
	private String url;
	private String custom1;
	private String custom2;
	private String custom3;
	private String custom4;
	private BigDecimal isBusinessEl;
	private String custom5;
	private String custom6;
	private String custom7;
	private String custom8;
	private String custom9;
	private String custom10;
	private String targetCycle;
	private BigDecimal testLevelId;
	private Set executionlistReleases = new HashSet(0);
	private Set testcaseExecutions = new HashSet(0);

	public ExecutionList() {
	}

	public ExecutionList(BigDecimal id, String name) {
		this.id = id;
		this.name = name;
	}

	public ExecutionList(BigDecimal id, String name, String sourceOrder, String folderName, String url, String custom1,
			String custom2, String custom3, String custom4, BigDecimal isBusinessEl, String custom5, String custom6,
			String custom7, String custom8, String custom9, String custom10, String targetCycle, BigDecimal testLevelId,
			Set executionlistReleases, Set testcaseExecutions) {
		this.id = id;
		this.name = name;
		this.sourceOrder = sourceOrder;
		this.folderName = folderName;
		this.url = url;
		this.custom1 = custom1;
		this.custom2 = custom2;
		this.custom3 = custom3;
		this.custom4 = custom4;
		this.isBusinessEl = isBusinessEl;
		this.custom5 = custom5;
		this.custom6 = custom6;
		this.custom7 = custom7;
		this.custom8 = custom8;
		this.custom9 = custom9;
		this.custom10 = custom10;
		this.targetCycle = targetCycle;
		this.testLevelId = testLevelId;
		this.executionlistReleases = executionlistReleases;
		this.testcaseExecutions = testcaseExecutions;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 1020)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SOURCE_ORDER", length = 1020)
	public String getSourceOrder() {
		return this.sourceOrder;
	}

	public void setSourceOrder(String sourceOrder) {
		this.sourceOrder = sourceOrder;
	}

	@Column(name = "FOLDER_NAME", length = 1020)
	public String getFolderName() {
		return this.folderName;
	}

	public void setFolderName(String folderName) {
		this.folderName = folderName;
	}

	@Column(name = "URL", length = 4000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "CUSTOM1", length = 4000)
	public String getCustom1() {
		return this.custom1;
	}

	public void setCustom1(String custom1) {
		this.custom1 = custom1;
	}

	@Column(name = "CUSTOM2", length = 4000)
	public String getCustom2() {
		return this.custom2;
	}

	public void setCustom2(String custom2) {
		this.custom2 = custom2;
	}

	@Column(name = "CUSTOM3", length = 4000)
	public String getCustom3() {
		return this.custom3;
	}

	public void setCustom3(String custom3) {
		this.custom3 = custom3;
	}

	@Column(name = "CUSTOM4", length = 4000)
	public String getCustom4() {
		return this.custom4;
	}

	public void setCustom4(String custom4) {
		this.custom4 = custom4;
	}

	@Column(name = "IS_BUSINESS_EL", precision = 22, scale = 0)
	public BigDecimal getIsBusinessEl() {
		return this.isBusinessEl;
	}

	public void setIsBusinessEl(BigDecimal isBusinessEl) {
		this.isBusinessEl = isBusinessEl;
	}

	@Column(name = "CUSTOM5", length = 4000)
	public String getCustom5() {
		return this.custom5;
	}

	public void setCustom5(String custom5) {
		this.custom5 = custom5;
	}

	@Column(name = "CUSTOM6", length = 4000)
	public String getCustom6() {
		return this.custom6;
	}

	public void setCustom6(String custom6) {
		this.custom6 = custom6;
	}

	@Column(name = "CUSTOM7", length = 4000)
	public String getCustom7() {
		return this.custom7;
	}

	public void setCustom7(String custom7) {
		this.custom7 = custom7;
	}

	@Column(name = "CUSTOM8", length = 4000)
	public String getCustom8() {
		return this.custom8;
	}

	public void setCustom8(String custom8) {
		this.custom8 = custom8;
	}

	@Column(name = "CUSTOM9", length = 4000)
	public String getCustom9() {
		return this.custom9;
	}

	public void setCustom9(String custom9) {
		this.custom9 = custom9;
	}

	@Column(name = "CUSTOM10", length = 4000)
	public String getCustom10() {
		return this.custom10;
	}

	public void setCustom10(String custom10) {
		this.custom10 = custom10;
	}

	@Column(name = "TARGET_CYCLE", length = 1020)
	public String getTargetCycle() {
		return this.targetCycle;
	}

	public void setTargetCycle(String targetCycle) {
		this.targetCycle = targetCycle;
	}

	@Column(name = "TEST_LEVEL_ID", precision = 38, scale = 0)
	public BigDecimal getTestLevelId() {
		return this.testLevelId;
	}

	public void setTestLevelId(BigDecimal testLevelId) {
		this.testLevelId = testLevelId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "executionList")
	public Set getExecutionlistReleases() {
		return this.executionlistReleases;
	}

	public void setExecutionlistReleases(Set executionlistReleases) {
		this.executionlistReleases = executionlistReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "executionList")
	public Set getTestcaseExecutions() {
		return this.testcaseExecutions;
	}

	public void setTestcaseExecutions(Set testcaseExecutions) {
		this.testcaseExecutions = testcaseExecutions;
	}

}
