package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ExecutionlistRelease generated by hbm2java
 */
@Entity
@Table(name = "EXECUTIONLIST_RELEASE", schema = "QACUBE_IMPORT_STAGE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"EXECUTIONLIST_ID", "PROJECT_ID", "RELEASE_ID" }))
public class ExecutionlistRelease implements java.io.Serializable {

	private ExecutionlistReleaseId id;
	private ExecutionList executionList;
	private Project project;
	private ProjectRelease projectRelease;

	public ExecutionlistRelease() {
	}

	public ExecutionlistRelease(ExecutionlistReleaseId id, ExecutionList executionList) {
		this.id = id;
		this.executionList = executionList;
	}

	public ExecutionlistRelease(ExecutionlistReleaseId id, ExecutionList executionList, Project project,
			ProjectRelease projectRelease) {
		this.id = id;
		this.executionList = executionList;
		this.project = project;
		this.projectRelease = projectRelease;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "executionlistId", column = @Column(name = "EXECUTIONLIST_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "projectId", column = @Column(name = "PROJECT_ID", precision = 38, scale = 0)),
			@AttributeOverride(name = "releaseId", column = @Column(name = "RELEASE_ID", precision = 38, scale = 0)) })
	public ExecutionlistReleaseId getId() {
		return this.id;
	}

	public void setId(ExecutionlistReleaseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXECUTIONLIST_ID", nullable = false, insertable = false, updatable = false)
	public ExecutionList getExecutionList() {
		return this.executionList;
	}

	public void setExecutionList(ExecutionList executionList) {
		this.executionList = executionList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", insertable = false, updatable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RELEASE_ID", insertable = false, updatable = false)
	public ProjectRelease getProjectRelease() {
		return this.projectRelease;
	}

	public void setProjectRelease(ProjectRelease projectRelease) {
		this.projectRelease = projectRelease;
	}

}
