package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "PROJECT", schema = "QACUBE_IMPORT_STAGE", uniqueConstraints = @UniqueConstraint(columnNames = { "NAME",
		"IS_APPLICATION" }))
public class Project implements java.io.Serializable {

	private BigDecimal id;
	private ProjectRelease projectRelease;
	private String name;
	private BigDecimal sourceId;
	private Date startDate;
	private Date endDate;
	private String sourceOrder;
	private String workspace;
	private BigDecimal connectionId;
	private BigDecimal isApplication;
	private Set executionlistReleases = new HashSet(0);
	private Set projectReleaseProjects = new HashSet(0);
	private Set defectTargetReleases = new HashSet(0);
	private Set testcaseReleases = new HashSet(0);
	private Set defectDetectedReleases = new HashSet(0);
	private Set requirementReleases = new HashSet(0);

	public Project() {
	}

	public Project(BigDecimal id, String name) {
		this.id = id;
		this.name = name;
	}

	public Project(BigDecimal id, ProjectRelease projectRelease, String name, BigDecimal sourceId, Date startDate,
			Date endDate, String sourceOrder, String workspace, BigDecimal connectionId, BigDecimal isApplication,
			Set executionlistReleases, Set projectReleaseProjects, Set defectTargetReleases, Set testcaseReleases,
			Set defectDetectedReleases, Set requirementReleases) {
		this.id = id;
		this.projectRelease = projectRelease;
		this.name = name;
		this.sourceId = sourceId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.sourceOrder = sourceOrder;
		this.workspace = workspace;
		this.connectionId = connectionId;
		this.isApplication = isApplication;
		this.executionlistReleases = executionlistReleases;
		this.projectReleaseProjects = projectReleaseProjects;
		this.defectTargetReleases = defectTargetReleases;
		this.testcaseReleases = testcaseReleases;
		this.defectDetectedReleases = defectDetectedReleases;
		this.requirementReleases = requirementReleases;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEFAULT_RELEASE_ID")
	public ProjectRelease getProjectRelease() {
		return this.projectRelease;
	}

	public void setProjectRelease(ProjectRelease projectRelease) {
		this.projectRelease = projectRelease;
	}

	@Column(name = "NAME", nullable = false, length = 1020)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SOURCE_ID", precision = 38, scale = 0)
	public BigDecimal getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(BigDecimal sourceId) {
		this.sourceId = sourceId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "SOURCE_ORDER", length = 1020)
	public String getSourceOrder() {
		return this.sourceOrder;
	}

	public void setSourceOrder(String sourceOrder) {
		this.sourceOrder = sourceOrder;
	}

	@Column(name = "WORKSPACE", length = 1020)
	public String getWorkspace() {
		return this.workspace;
	}

	public void setWorkspace(String workspace) {
		this.workspace = workspace;
	}

	@Column(name = "CONNECTION_ID", precision = 22, scale = 0)
	public BigDecimal getConnectionId() {
		return this.connectionId;
	}

	public void setConnectionId(BigDecimal connectionId) {
		this.connectionId = connectionId;
	}

	@Column(name = "IS_APPLICATION", precision = 22, scale = 0)
	public BigDecimal getIsApplication() {
		return this.isApplication;
	}

	public void setIsApplication(BigDecimal isApplication) {
		this.isApplication = isApplication;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set getExecutionlistReleases() {
		return this.executionlistReleases;
	}

	public void setExecutionlistReleases(Set executionlistReleases) {
		this.executionlistReleases = executionlistReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set getProjectReleaseProjects() {
		return this.projectReleaseProjects;
	}

	public void setProjectReleaseProjects(Set projectReleaseProjects) {
		this.projectReleaseProjects = projectReleaseProjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set getDefectTargetReleases() {
		return this.defectTargetReleases;
	}

	public void setDefectTargetReleases(Set defectTargetReleases) {
		this.defectTargetReleases = defectTargetReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set getTestcaseReleases() {
		return this.testcaseReleases;
	}

	public void setTestcaseReleases(Set testcaseReleases) {
		this.testcaseReleases = testcaseReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set getDefectDetectedReleases() {
		return this.defectDetectedReleases;
	}

	public void setDefectDetectedReleases(Set defectDetectedReleases) {
		this.defectDetectedReleases = defectDetectedReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set getRequirementReleases() {
		return this.requirementReleases;
	}

	public void setRequirementReleases(Set requirementReleases) {
		this.requirementReleases = requirementReleases;
	}

}
