package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ProjectRelease generated by hbm2java
 */
@Entity
@Table(name = "PROJECT_RELEASE", schema = "QACUBE_IMPORT_STAGE", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class ProjectRelease implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private Date startDate;
	private Date endDate;
	private String sourceOrder;
	private String url;
	private String description;
	private Set projects = new HashSet(0);
	private Set testcaseReleases = new HashSet(0);
	private Set defectTargetReleases = new HashSet(0);
	private Set projectReleaseProjects = new HashSet(0);
	private Set requirementReleases = new HashSet(0);
	private Set defectDetectedReleases = new HashSet(0);
	private Set defects = new HashSet(0);
	private Set executionlistReleases = new HashSet(0);

	public ProjectRelease() {
	}

	public ProjectRelease(BigDecimal id) {
		this.id = id;
	}

	public ProjectRelease(BigDecimal id, String name, Date startDate, Date endDate, String sourceOrder, String url,
			String description, Set projects, Set testcaseReleases, Set defectTargetReleases,
			Set projectReleaseProjects, Set requirementReleases, Set defectDetectedReleases, Set defects,
			Set executionlistReleases) {
		this.id = id;
		this.name = name;
		this.startDate = startDate;
		this.endDate = endDate;
		this.sourceOrder = sourceOrder;
		this.url = url;
		this.description = description;
		this.projects = projects;
		this.testcaseReleases = testcaseReleases;
		this.defectTargetReleases = defectTargetReleases;
		this.projectReleaseProjects = projectReleaseProjects;
		this.requirementReleases = requirementReleases;
		this.defectDetectedReleases = defectDetectedReleases;
		this.defects = defects;
		this.executionlistReleases = executionlistReleases;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, length = 1020)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "SOURCE_ORDER", length = 1020)
	public String getSourceOrder() {
		return this.sourceOrder;
	}

	public void setSourceOrder(String sourceOrder) {
		this.sourceOrder = sourceOrder;
	}

	@Column(name = "URL", length = 4000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRelease")
	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRelease")
	public Set getTestcaseReleases() {
		return this.testcaseReleases;
	}

	public void setTestcaseReleases(Set testcaseReleases) {
		this.testcaseReleases = testcaseReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRelease")
	public Set getDefectTargetReleases() {
		return this.defectTargetReleases;
	}

	public void setDefectTargetReleases(Set defectTargetReleases) {
		this.defectTargetReleases = defectTargetReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRelease")
	public Set getProjectReleaseProjects() {
		return this.projectReleaseProjects;
	}

	public void setProjectReleaseProjects(Set projectReleaseProjects) {
		this.projectReleaseProjects = projectReleaseProjects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRelease")
	public Set getRequirementReleases() {
		return this.requirementReleases;
	}

	public void setRequirementReleases(Set requirementReleases) {
		this.requirementReleases = requirementReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRelease")
	public Set getDefectDetectedReleases() {
		return this.defectDetectedReleases;
	}

	public void setDefectDetectedReleases(Set defectDetectedReleases) {
		this.defectDetectedReleases = defectDetectedReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRelease")
	public Set getDefects() {
		return this.defects;
	}

	public void setDefects(Set defects) {
		this.defects = defects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectRelease")
	public Set getExecutionlistReleases() {
		return this.executionlistReleases;
	}

	public void setExecutionlistReleases(Set executionlistReleases) {
		this.executionlistReleases = executionlistReleases;
	}

}
