package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectReleaseProjectId generated by hbm2java
 */
@Embeddable
public class ProjectReleaseProjectId implements java.io.Serializable {

	private BigDecimal releaseId;
	private BigDecimal projectId;

	public ProjectReleaseProjectId() {
	}

	public ProjectReleaseProjectId(BigDecimal releaseId, BigDecimal projectId) {
		this.releaseId = releaseId;
		this.projectId = projectId;
	}

	@Column(name = "RELEASE_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(BigDecimal releaseId) {
		this.releaseId = releaseId;
	}

	@Column(name = "PROJECT_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectReleaseProjectId))
			return false;
		ProjectReleaseProjectId castOther = (ProjectReleaseProjectId) other;

		return ((this.getReleaseId() == castOther.getReleaseId()) || (this.getReleaseId() != null
				&& castOther.getReleaseId() != null && this.getReleaseId().equals(castOther.getReleaseId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getReleaseId() == null ? 0 : this.getReleaseId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		return result;
	}

}
