package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QTaskStatus generated by hbm2java
 */
@Entity
@Table(name = "Q_TASK_STATUS", schema = "QACUBE_IMPORT_STAGE")
public class QTaskStatus implements java.io.Serializable {

	private BigDecimal id;
	private String value;

	public QTaskStatus() {
	}

	public QTaskStatus(BigDecimal id, String value) {
		this.id = id;
		this.value = value;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "VALUE", nullable = false, length = 1020)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
