package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QTestcaseStatus generated by hbm2java
 */
@Entity
@Table(name = "Q_TESTCASE_STATUS", schema = "QACUBE_IMPORT_STAGE")
public class QTestcaseStatus implements java.io.Serializable {

	private BigDecimal id;
	private String value;
	private BigDecimal statusOrder;
	private Set testcaseDefects = new HashSet(0);
	private Set testcaseRequirements = new HashSet(0);
	private Set testcaseExecutions = new HashSet(0);

	public QTestcaseStatus() {
	}

	public QTestcaseStatus(BigDecimal id, String value) {
		this.id = id;
		this.value = value;
	}

	public QTestcaseStatus(BigDecimal id, String value, BigDecimal statusOrder, Set testcaseDefects,
			Set testcaseRequirements, Set testcaseExecutions) {
		this.id = id;
		this.value = value;
		this.statusOrder = statusOrder;
		this.testcaseDefects = testcaseDefects;
		this.testcaseRequirements = testcaseRequirements;
		this.testcaseExecutions = testcaseExecutions;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "VALUE", nullable = false, length = 1020)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "STATUS_ORDER", precision = 22, scale = 0)
	public BigDecimal getStatusOrder() {
		return this.statusOrder;
	}

	public void setStatusOrder(BigDecimal statusOrder) {
		this.statusOrder = statusOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "QTestcaseStatus")
	public Set getTestcaseDefects() {
		return this.testcaseDefects;
	}

	public void setTestcaseDefects(Set testcaseDefects) {
		this.testcaseDefects = testcaseDefects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "QTestcaseStatus")
	public Set getTestcaseRequirements() {
		return this.testcaseRequirements;
	}

	public void setTestcaseRequirements(Set testcaseRequirements) {
		this.testcaseRequirements = testcaseRequirements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "QTestcaseStatus")
	public Set getTestcaseExecutions() {
		return this.testcaseExecutions;
	}

	public void setTestcaseExecutions(Set testcaseExecutions) {
		this.testcaseExecutions = testcaseExecutions;
	}

}
