package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QTestcaseWorkstate generated by hbm2java
 */
@Entity
@Table(name = "Q_TESTCASE_WORKSTATE", schema = "QACUBE_IMPORT_STAGE")
public class QTestcaseWorkstate implements java.io.Serializable {

	private BigDecimal id;
	private String value;
	private Set testcases = new HashSet(0);

	public QTestcaseWorkstate() {
	}

	public QTestcaseWorkstate(BigDecimal id, String value) {
		this.id = id;
		this.value = value;
	}

	public QTestcaseWorkstate(BigDecimal id, String value, Set testcases) {
		this.id = id;
		this.value = value;
		this.testcases = testcases;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "VALUE", nullable = false, length = 1020)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "QTestcaseWorkstate")
	public Set getTestcases() {
		return this.testcases;
	}

	public void setTestcases(Set testcases) {
		this.testcases = testcases;
	}

}
