package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RequirementDefectId generated by hbm2java
 */
@Embeddable
public class RequirementDefectId implements java.io.Serializable {

	private BigDecimal requirementId;
	private BigDecimal defectId;

	public RequirementDefectId() {
	}

	public RequirementDefectId(BigDecimal requirementId, BigDecimal defectId) {
		this.requirementId = requirementId;
		this.defectId = defectId;
	}

	@Column(name = "REQUIREMENT_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getRequirementId() {
		return this.requirementId;
	}

	public void setRequirementId(BigDecimal requirementId) {
		this.requirementId = requirementId;
	}

	@Column(name = "DEFECT_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getDefectId() {
		return this.defectId;
	}

	public void setDefectId(BigDecimal defectId) {
		this.defectId = defectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RequirementDefectId))
			return false;
		RequirementDefectId castOther = (RequirementDefectId) other;

		return ((this.getRequirementId() == castOther.getRequirementId())
				|| (this.getRequirementId() != null && castOther.getRequirementId() != null
						&& this.getRequirementId().equals(castOther.getRequirementId())))
				&& ((this.getDefectId() == castOther.getDefectId()) || (this.getDefectId() != null
						&& castOther.getDefectId() != null && this.getDefectId().equals(castOther.getDefectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRequirementId() == null ? 0 : this.getRequirementId().hashCode());
		result = 37 * result + (getDefectId() == null ? 0 : this.getDefectId().hashCode());
		return result;
	}

}
