package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RequirementReleaseId generated by hbm2java
 */
@Embeddable
public class RequirementReleaseId implements java.io.Serializable {

	private BigDecimal requirementId;
	private BigDecimal projectId;
	private BigDecimal releaseId;

	public RequirementReleaseId() {
	}

	public RequirementReleaseId(BigDecimal requirementId, BigDecimal projectId) {
		this.requirementId = requirementId;
		this.projectId = projectId;
	}

	public RequirementReleaseId(BigDecimal requirementId, BigDecimal projectId, BigDecimal releaseId) {
		this.requirementId = requirementId;
		this.projectId = projectId;
		this.releaseId = releaseId;
	}

	@Column(name = "REQUIREMENT_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getRequirementId() {
		return this.requirementId;
	}

	public void setRequirementId(BigDecimal requirementId) {
		this.requirementId = requirementId;
	}

	@Column(name = "PROJECT_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	@Column(name = "RELEASE_ID", precision = 38, scale = 0)
	public BigDecimal getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(BigDecimal releaseId) {
		this.releaseId = releaseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RequirementReleaseId))
			return false;
		RequirementReleaseId castOther = (RequirementReleaseId) other;

		return ((this.getRequirementId() == castOther.getRequirementId())
				|| (this.getRequirementId() != null && castOther.getRequirementId() != null
						&& this.getRequirementId().equals(castOther.getRequirementId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getReleaseId() == castOther.getReleaseId()) || (this.getReleaseId() != null
						&& castOther.getReleaseId() != null && this.getReleaseId().equals(castOther.getReleaseId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRequirementId() == null ? 0 : this.getRequirementId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getReleaseId() == null ? 0 : this.getReleaseId().hashCode());
		return result;
	}

}
