package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RequirementDefect generated by hbm2java
 */
@Entity
@Table(name = "REQUIREMENT_DEFECT", schema = "QACUBE_IMPORT_STAGE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"REQUIREMENT_ID", "DEFECT_ID" }))
public class RequirementDefect implements java.io.Serializable {

	private RequirementDefectId id;
	private Defect defect;
	private Requirement requirement;

	public RequirementDefect() {
	}

	public RequirementDefect(RequirementDefectId id, Defect defect, Requirement requirement) {
		this.id = id;
		this.defect = defect;
		this.requirement = requirement;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "requirementId", column = @Column(name = "REQUIREMENT_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "defectId", column = @Column(name = "DEFECT_ID", nullable = false, precision = 38, scale = 0)) })
	public RequirementDefectId getId() {
		return this.id;
	}

	public void setId(RequirementDefectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEFECT_ID", nullable = false, insertable = false, updatable = false)
	public Defect getDefect() {
		return this.defect;
	}

	public void setDefect(Defect defect) {
		this.defect = defect;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQUIREMENT_ID", nullable = false, insertable = false, updatable = false)
	public Requirement getRequirement() {
		return this.requirement;
	}

	public void setRequirement(Requirement requirement) {
		this.requirement = requirement;
	}

}
