package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RequirementRelease generated by hbm2java
 */
@Entity
@Table(name = "REQUIREMENT_RELEASE", schema = "QACUBE_IMPORT_STAGE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"REQUIREMENT_ID", "PROJECT_ID", "RELEASE_ID" }))
public class RequirementRelease implements java.io.Serializable {

	private RequirementReleaseId id;
	private Project project;
	private ProjectRelease projectRelease;
	private Requirement requirement;

	public RequirementRelease() {
	}

	public RequirementRelease(RequirementReleaseId id, Project project, Requirement requirement) {
		this.id = id;
		this.project = project;
		this.requirement = requirement;
	}

	public RequirementRelease(RequirementReleaseId id, Project project, ProjectRelease projectRelease,
			Requirement requirement) {
		this.id = id;
		this.project = project;
		this.projectRelease = projectRelease;
		this.requirement = requirement;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "requirementId", column = @Column(name = "REQUIREMENT_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "projectId", column = @Column(name = "PROJECT_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "releaseId", column = @Column(name = "RELEASE_ID", precision = 38, scale = 0)) })
	public RequirementReleaseId getId() {
		return this.id;
	}

	public void setId(RequirementReleaseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false, insertable = false, updatable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RELEASE_ID", insertable = false, updatable = false)
	public ProjectRelease getProjectRelease() {
		return this.projectRelease;
	}

	public void setProjectRelease(ProjectRelease projectRelease) {
		this.projectRelease = projectRelease;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQUIREMENT_ID", nullable = false, insertable = false, updatable = false)
	public Requirement getRequirement() {
		return this.requirement;
	}

	public void setRequirement(Requirement requirement) {
		this.requirement = requirement;
	}

}
