package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TestcaseExecutionId generated by hbm2java
 */
@Embeddable
public class TestcaseExecutionId implements java.io.Serializable {

	private BigDecimal testcaseId;
	private BigDecimal executionListId;
	private BigDecimal environmentId;
	private Serializable plannedTimestamp;
	private Serializable executedTimestamp;
	private BigDecimal testcaseStatusId;
	private BigDecimal duration;
	private BigDecimal phaseId;
	private BigDecimal cycleId;
	private BigDecimal releaseId;
	private String executedBy;
	private String executionEnvironment;
	private BigDecimal testcasePriorityId;

	public TestcaseExecutionId() {
	}

	public TestcaseExecutionId(BigDecimal testcaseId, BigDecimal testcaseStatusId) {
		this.testcaseId = testcaseId;
		this.testcaseStatusId = testcaseStatusId;
	}

	public TestcaseExecutionId(BigDecimal testcaseId, BigDecimal executionListId, BigDecimal environmentId,
			Serializable plannedTimestamp, Serializable executedTimestamp, BigDecimal testcaseStatusId,
			BigDecimal duration, BigDecimal phaseId, BigDecimal cycleId, BigDecimal releaseId, String executedBy,
			String executionEnvironment, BigDecimal testcasePriorityId) {
		this.testcaseId = testcaseId;
		this.executionListId = executionListId;
		this.environmentId = environmentId;
		this.plannedTimestamp = plannedTimestamp;
		this.executedTimestamp = executedTimestamp;
		this.testcaseStatusId = testcaseStatusId;
		this.duration = duration;
		this.phaseId = phaseId;
		this.cycleId = cycleId;
		this.releaseId = releaseId;
		this.executedBy = executedBy;
		this.executionEnvironment = executionEnvironment;
		this.testcasePriorityId = testcasePriorityId;
	}

	@Column(name = "TESTCASE_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getTestcaseId() {
		return this.testcaseId;
	}

	public void setTestcaseId(BigDecimal testcaseId) {
		this.testcaseId = testcaseId;
	}

	@Column(name = "EXECUTION_LIST_ID", precision = 38, scale = 0)
	public BigDecimal getExecutionListId() {
		return this.executionListId;
	}

	public void setExecutionListId(BigDecimal executionListId) {
		this.executionListId = executionListId;
	}

	@Column(name = "ENVIRONMENT_ID", precision = 38, scale = 0)
	public BigDecimal getEnvironmentId() {
		return this.environmentId;
	}

	public void setEnvironmentId(BigDecimal environmentId) {
		this.environmentId = environmentId;
	}

	@Column(name = "PLANNED_TIMESTAMP")
	public Serializable getPlannedTimestamp() {
		return this.plannedTimestamp;
	}

	public void setPlannedTimestamp(Serializable plannedTimestamp) {
		this.plannedTimestamp = plannedTimestamp;
	}

	@Column(name = "EXECUTED_TIMESTAMP")
	public Serializable getExecutedTimestamp() {
		return this.executedTimestamp;
	}

	public void setExecutedTimestamp(Serializable executedTimestamp) {
		this.executedTimestamp = executedTimestamp;
	}

	@Column(name = "TESTCASE_STATUS_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getTestcaseStatusId() {
		return this.testcaseStatusId;
	}

	public void setTestcaseStatusId(BigDecimal testcaseStatusId) {
		this.testcaseStatusId = testcaseStatusId;
	}

	@Column(name = "DURATION", precision = 22, scale = 0)
	public BigDecimal getDuration() {
		return this.duration;
	}

	public void setDuration(BigDecimal duration) {
		this.duration = duration;
	}

	@Column(name = "PHASE_ID", precision = 38, scale = 0)
	public BigDecimal getPhaseId() {
		return this.phaseId;
	}

	public void setPhaseId(BigDecimal phaseId) {
		this.phaseId = phaseId;
	}

	@Column(name = "CYCLE_ID", precision = 38, scale = 0)
	public BigDecimal getCycleId() {
		return this.cycleId;
	}

	public void setCycleId(BigDecimal cycleId) {
		this.cycleId = cycleId;
	}

	@Column(name = "RELEASE_ID", precision = 38, scale = 0)
	public BigDecimal getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(BigDecimal releaseId) {
		this.releaseId = releaseId;
	}

	@Column(name = "EXECUTED_BY", length = 1020)
	public String getExecutedBy() {
		return this.executedBy;
	}

	public void setExecutedBy(String executedBy) {
		this.executedBy = executedBy;
	}

	@Column(name = "EXECUTION_ENVIRONMENT", length = 1020)
	public String getExecutionEnvironment() {
		return this.executionEnvironment;
	}

	public void setExecutionEnvironment(String executionEnvironment) {
		this.executionEnvironment = executionEnvironment;
	}

	@Column(name = "TESTCASE_PRIORITY_ID", precision = 38, scale = 0)
	public BigDecimal getTestcasePriorityId() {
		return this.testcasePriorityId;
	}

	public void setTestcasePriorityId(BigDecimal testcasePriorityId) {
		this.testcasePriorityId = testcasePriorityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestcaseExecutionId))
			return false;
		TestcaseExecutionId castOther = (TestcaseExecutionId) other;

		return ((this.getTestcaseId() == castOther.getTestcaseId()) || (this.getTestcaseId() != null
				&& castOther.getTestcaseId() != null && this.getTestcaseId().equals(castOther.getTestcaseId())))
				&& ((this.getExecutionListId() == castOther.getExecutionListId())
						|| (this.getExecutionListId() != null && castOther.getExecutionListId() != null
								&& this.getExecutionListId().equals(castOther.getExecutionListId())))
				&& ((this.getEnvironmentId() == castOther.getEnvironmentId())
						|| (this.getEnvironmentId() != null && castOther.getEnvironmentId() != null
								&& this.getEnvironmentId().equals(castOther.getEnvironmentId())))
				&& ((this.getPlannedTimestamp() == castOther.getPlannedTimestamp())
						|| (this.getPlannedTimestamp() != null && castOther.getPlannedTimestamp() != null
								&& this.getPlannedTimestamp().equals(castOther.getPlannedTimestamp())))
				&& ((this.getExecutedTimestamp() == castOther.getExecutedTimestamp())
						|| (this.getExecutedTimestamp() != null && castOther.getExecutedTimestamp() != null
								&& this.getExecutedTimestamp().equals(castOther.getExecutedTimestamp())))
				&& ((this.getTestcaseStatusId() == castOther.getTestcaseStatusId())
						|| (this.getTestcaseStatusId() != null && castOther.getTestcaseStatusId() != null
								&& this.getTestcaseStatusId().equals(castOther.getTestcaseStatusId())))
				&& ((this.getDuration() == castOther.getDuration()) || (this.getDuration() != null
						&& castOther.getDuration() != null && this.getDuration().equals(castOther.getDuration())))
				&& ((this.getPhaseId() == castOther.getPhaseId()) || (this.getPhaseId() != null
						&& castOther.getPhaseId() != null && this.getPhaseId().equals(castOther.getPhaseId())))
				&& ((this.getCycleId() == castOther.getCycleId()) || (this.getCycleId() != null
						&& castOther.getCycleId() != null && this.getCycleId().equals(castOther.getCycleId())))
				&& ((this.getReleaseId() == castOther.getReleaseId()) || (this.getReleaseId() != null
						&& castOther.getReleaseId() != null && this.getReleaseId().equals(castOther.getReleaseId())))
				&& ((this.getExecutedBy() == castOther.getExecutedBy()) || (this.getExecutedBy() != null
						&& castOther.getExecutedBy() != null && this.getExecutedBy().equals(castOther.getExecutedBy())))
				&& ((this.getExecutionEnvironment() == castOther.getExecutionEnvironment())
						|| (this.getExecutionEnvironment() != null && castOther.getExecutionEnvironment() != null
								&& this.getExecutionEnvironment().equals(castOther.getExecutionEnvironment())))
				&& ((this.getTestcasePriorityId() == castOther.getTestcasePriorityId())
						|| (this.getTestcasePriorityId() != null && castOther.getTestcasePriorityId() != null
								&& this.getTestcasePriorityId().equals(castOther.getTestcasePriorityId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTestcaseId() == null ? 0 : this.getTestcaseId().hashCode());
		result = 37 * result + (getExecutionListId() == null ? 0 : this.getExecutionListId().hashCode());
		result = 37 * result + (getEnvironmentId() == null ? 0 : this.getEnvironmentId().hashCode());
		result = 37 * result + (getPlannedTimestamp() == null ? 0 : this.getPlannedTimestamp().hashCode());
		result = 37 * result + (getExecutedTimestamp() == null ? 0 : this.getExecutedTimestamp().hashCode());
		result = 37 * result + (getTestcaseStatusId() == null ? 0 : this.getTestcaseStatusId().hashCode());
		result = 37 * result + (getDuration() == null ? 0 : this.getDuration().hashCode());
		result = 37 * result + (getPhaseId() == null ? 0 : this.getPhaseId().hashCode());
		result = 37 * result + (getCycleId() == null ? 0 : this.getCycleId().hashCode());
		result = 37 * result + (getReleaseId() == null ? 0 : this.getReleaseId().hashCode());
		result = 37 * result + (getExecutedBy() == null ? 0 : this.getExecutedBy().hashCode());
		result = 37 * result + (getExecutionEnvironment() == null ? 0 : this.getExecutionEnvironment().hashCode());
		result = 37 * result + (getTestcasePriorityId() == null ? 0 : this.getTestcasePriorityId().hashCode());
		return result;
	}

}
