package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestcaseExecution generated by hbm2java
 */
@Entity
@Table(name = "TESTCASE_EXECUTION", schema = "QACUBE_IMPORT_STAGE")
public class TestcaseExecution implements java.io.Serializable {

	private TestcaseExecutionId id;
	private ExecutionList executionList;
	private QTestcaseStatus QTestcaseStatus;
	private Testcase testcase;

	public TestcaseExecution() {
	}

	public TestcaseExecution(TestcaseExecutionId id, QTestcaseStatus QTestcaseStatus, Testcase testcase) {
		this.id = id;
		this.QTestcaseStatus = QTestcaseStatus;
		this.testcase = testcase;
	}

	public TestcaseExecution(TestcaseExecutionId id, ExecutionList executionList, QTestcaseStatus QTestcaseStatus,
			Testcase testcase) {
		this.id = id;
		this.executionList = executionList;
		this.QTestcaseStatus = QTestcaseStatus;
		this.testcase = testcase;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "testcaseId", column = @Column(name = "TESTCASE_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "executionListId", column = @Column(name = "EXECUTION_LIST_ID", precision = 38, scale = 0)),
			@AttributeOverride(name = "environmentId", column = @Column(name = "ENVIRONMENT_ID", precision = 38, scale = 0)),
			@AttributeOverride(name = "plannedTimestamp", column = @Column(name = "PLANNED_TIMESTAMP")),
			@AttributeOverride(name = "executedTimestamp", column = @Column(name = "EXECUTED_TIMESTAMP")),
			@AttributeOverride(name = "testcaseStatusId", column = @Column(name = "TESTCASE_STATUS_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "duration", column = @Column(name = "DURATION", precision = 22, scale = 0)),
			@AttributeOverride(name = "phaseId", column = @Column(name = "PHASE_ID", precision = 38, scale = 0)),
			@AttributeOverride(name = "cycleId", column = @Column(name = "CYCLE_ID", precision = 38, scale = 0)),
			@AttributeOverride(name = "releaseId", column = @Column(name = "RELEASE_ID", precision = 38, scale = 0)),
			@AttributeOverride(name = "executedBy", column = @Column(name = "EXECUTED_BY", length = 1020)),
			@AttributeOverride(name = "executionEnvironment", column = @Column(name = "EXECUTION_ENVIRONMENT", length = 1020)),
			@AttributeOverride(name = "testcasePriorityId", column = @Column(name = "TESTCASE_PRIORITY_ID", precision = 38, scale = 0)) })
	public TestcaseExecutionId getId() {
		return this.id;
	}

	public void setId(TestcaseExecutionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXECUTION_LIST_ID", insertable = false, updatable = false)
	public ExecutionList getExecutionList() {
		return this.executionList;
	}

	public void setExecutionList(ExecutionList executionList) {
		this.executionList = executionList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TESTCASE_STATUS_ID", nullable = false, insertable = false, updatable = false)
	public QTestcaseStatus getQTestcaseStatus() {
		return this.QTestcaseStatus;
	}

	public void setQTestcaseStatus(QTestcaseStatus QTestcaseStatus) {
		this.QTestcaseStatus = QTestcaseStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TESTCASE_ID", nullable = false, insertable = false, updatable = false)
	public Testcase getTestcase() {
		return this.testcase;
	}

	public void setTestcase(Testcase testcase) {
		this.testcase = testcase;
	}

}
