package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TestcaseReleaseId generated by hbm2java
 */
@Embeddable
public class TestcaseReleaseId implements java.io.Serializable {

	private BigDecimal testcaseId;
	private BigDecimal projectId;
	private BigDecimal releaseId;

	public TestcaseReleaseId() {
	}

	public TestcaseReleaseId(BigDecimal testcaseId, BigDecimal projectId) {
		this.testcaseId = testcaseId;
		this.projectId = projectId;
	}

	public TestcaseReleaseId(BigDecimal testcaseId, BigDecimal projectId, BigDecimal releaseId) {
		this.testcaseId = testcaseId;
		this.projectId = projectId;
		this.releaseId = releaseId;
	}

	@Column(name = "TESTCASE_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getTestcaseId() {
		return this.testcaseId;
	}

	public void setTestcaseId(BigDecimal testcaseId) {
		this.testcaseId = testcaseId;
	}

	@Column(name = "PROJECT_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	@Column(name = "RELEASE_ID", precision = 38, scale = 0)
	public BigDecimal getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(BigDecimal releaseId) {
		this.releaseId = releaseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestcaseReleaseId))
			return false;
		TestcaseReleaseId castOther = (TestcaseReleaseId) other;

		return ((this.getTestcaseId() == castOther.getTestcaseId()) || (this.getTestcaseId() != null
				&& castOther.getTestcaseId() != null && this.getTestcaseId().equals(castOther.getTestcaseId())))
				&& ((this.getProjectId() == castOther.getProjectId()) || (this.getProjectId() != null
						&& castOther.getProjectId() != null && this.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getReleaseId() == castOther.getReleaseId()) || (this.getReleaseId() != null
						&& castOther.getReleaseId() != null && this.getReleaseId().equals(castOther.getReleaseId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTestcaseId() == null ? 0 : this.getTestcaseId().hashCode());
		result = 37 * result + (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result + (getReleaseId() == null ? 0 : this.getReleaseId().hashCode());
		return result;
	}

}
