package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TestcaseRequirementId generated by hbm2java
 */
@Embeddable
public class TestcaseRequirementId implements java.io.Serializable {

	private BigDecimal testcaseId;
	private BigDecimal requirementId;
	private BigDecimal testcaseStatusId;
	private BigDecimal weight;

	public TestcaseRequirementId() {
	}

	public TestcaseRequirementId(BigDecimal testcaseId, BigDecimal requirementId) {
		this.testcaseId = testcaseId;
		this.requirementId = requirementId;
	}

	public TestcaseRequirementId(BigDecimal testcaseId, BigDecimal requirementId, BigDecimal testcaseStatusId,
			BigDecimal weight) {
		this.testcaseId = testcaseId;
		this.requirementId = requirementId;
		this.testcaseStatusId = testcaseStatusId;
		this.weight = weight;
	}

	@Column(name = "TESTCASE_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getTestcaseId() {
		return this.testcaseId;
	}

	public void setTestcaseId(BigDecimal testcaseId) {
		this.testcaseId = testcaseId;
	}

	@Column(name = "REQUIREMENT_ID", nullable = false, precision = 38, scale = 0)
	public BigDecimal getRequirementId() {
		return this.requirementId;
	}

	public void setRequirementId(BigDecimal requirementId) {
		this.requirementId = requirementId;
	}

	@Column(name = "TESTCASE_STATUS_ID", precision = 38, scale = 0)
	public BigDecimal getTestcaseStatusId() {
		return this.testcaseStatusId;
	}

	public void setTestcaseStatusId(BigDecimal testcaseStatusId) {
		this.testcaseStatusId = testcaseStatusId;
	}

	@Column(name = "WEIGHT", precision = 22, scale = 0)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestcaseRequirementId))
			return false;
		TestcaseRequirementId castOther = (TestcaseRequirementId) other;

		return ((this.getTestcaseId() == castOther.getTestcaseId()) || (this.getTestcaseId() != null
				&& castOther.getTestcaseId() != null && this.getTestcaseId().equals(castOther.getTestcaseId())))
				&& ((this.getRequirementId() == castOther.getRequirementId())
						|| (this.getRequirementId() != null && castOther.getRequirementId() != null
								&& this.getRequirementId().equals(castOther.getRequirementId())))
				&& ((this.getTestcaseStatusId() == castOther.getTestcaseStatusId())
						|| (this.getTestcaseStatusId() != null && castOther.getTestcaseStatusId() != null
								&& this.getTestcaseStatusId().equals(castOther.getTestcaseStatusId())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null
						&& castOther.getWeight() != null && this.getWeight().equals(castOther.getWeight())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTestcaseId() == null ? 0 : this.getTestcaseId().hashCode());
		result = 37 * result + (getRequirementId() == null ? 0 : this.getRequirementId().hashCode());
		result = 37 * result + (getTestcaseStatusId() == null ? 0 : this.getTestcaseStatusId().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		return result;
	}

}
