package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TestcaseRelease generated by hbm2java
 */
@Entity
@Table(name = "TESTCASE_RELEASE", schema = "QACUBE_IMPORT_STAGE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"TESTCASE_ID", "PROJECT_ID", "RELEASE_ID" }))
public class TestcaseRelease implements java.io.Serializable {

	private TestcaseReleaseId id;
	private Project project;
	private ProjectRelease projectRelease;
	private Testcase testcase;

	public TestcaseRelease() {
	}

	public TestcaseRelease(TestcaseReleaseId id, Project project, Testcase testcase) {
		this.id = id;
		this.project = project;
		this.testcase = testcase;
	}

	public TestcaseRelease(TestcaseReleaseId id, Project project, ProjectRelease projectRelease, Testcase testcase) {
		this.id = id;
		this.project = project;
		this.projectRelease = projectRelease;
		this.testcase = testcase;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "testcaseId", column = @Column(name = "TESTCASE_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "projectId", column = @Column(name = "PROJECT_ID", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "releaseId", column = @Column(name = "RELEASE_ID", precision = 38, scale = 0)) })
	public TestcaseReleaseId getId() {
		return this.id;
	}

	public void setId(TestcaseReleaseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false, insertable = false, updatable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RELEASE_ID", insertable = false, updatable = false)
	public ProjectRelease getProjectRelease() {
		return this.projectRelease;
	}

	public void setProjectRelease(ProjectRelease projectRelease) {
		this.projectRelease = projectRelease;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TESTCASE_ID", nullable = false, insertable = false, updatable = false)
	public Testcase getTestcase() {
		return this.testcase;
	}

	public void setTestcase(Testcase testcase) {
		this.testcase = testcase;
	}

}
