package qacubeHbnFiles;
// Generated Jul 25, 2019 2:13:06 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testcase generated by hbm2java
 */
@Entity
@Table(name = "TESTCASE", schema = "QACUBE_IMPORT_STAGE")
public class Testcase implements java.io.Serializable {

	private BigDecimal id;
	private QTestcaseWorkstate QTestcaseWorkstate;
	private String name;
	private BigDecimal isBusinessTestcase;
	private String description;
	private BigDecimal testcaseAutomationId;
	private BigDecimal testcaseTypeId;
	private BigDecimal parentId;
	private String sourceOrder;
	private BigDecimal testcasePriorityId;
	private String url;
	private String custom1;
	private String custom2;
	private String custom3;
	private String custom4;
	private String externalEntityId;
	private BigDecimal testStepsCount;
	private String targetEntityId;
	private String custom5;
	private String custom6;
	private String custom7;
	private String custom8;
	private String custom9;
	private String custom10;
	private BigDecimal isRegressionBasic;
	private BigDecimal testLevelId;
	private String extReference;
	private BigDecimal testcaseRegressionTypeId;
	private Set testcaseExecutions = new HashSet(0);
	private Set testcaseRequirements = new HashSet(0);
	private Set testcaseReleases = new HashSet(0);
	private Set testcaseDefects = new HashSet(0);

	public Testcase() {
	}

	public Testcase(BigDecimal id, String name) {
		this.id = id;
		this.name = name;
	}

	public Testcase(BigDecimal id, QTestcaseWorkstate QTestcaseWorkstate, String name, BigDecimal isBusinessTestcase,
			String description, BigDecimal testcaseAutomationId, BigDecimal testcaseTypeId, BigDecimal parentId,
			String sourceOrder, BigDecimal testcasePriorityId, String url, String custom1, String custom2,
			String custom3, String custom4, String externalEntityId, BigDecimal testStepsCount, String targetEntityId,
			String custom5, String custom6, String custom7, String custom8, String custom9, String custom10,
			BigDecimal isRegressionBasic, BigDecimal testLevelId, String extReference,
			BigDecimal testcaseRegressionTypeId, Set testcaseExecutions, Set testcaseRequirements, Set testcaseReleases,
			Set testcaseDefects) {
		this.id = id;
		this.QTestcaseWorkstate = QTestcaseWorkstate;
		this.name = name;
		this.isBusinessTestcase = isBusinessTestcase;
		this.description = description;
		this.testcaseAutomationId = testcaseAutomationId;
		this.testcaseTypeId = testcaseTypeId;
		this.parentId = parentId;
		this.sourceOrder = sourceOrder;
		this.testcasePriorityId = testcasePriorityId;
		this.url = url;
		this.custom1 = custom1;
		this.custom2 = custom2;
		this.custom3 = custom3;
		this.custom4 = custom4;
		this.externalEntityId = externalEntityId;
		this.testStepsCount = testStepsCount;
		this.targetEntityId = targetEntityId;
		this.custom5 = custom5;
		this.custom6 = custom6;
		this.custom7 = custom7;
		this.custom8 = custom8;
		this.custom9 = custom9;
		this.custom10 = custom10;
		this.isRegressionBasic = isRegressionBasic;
		this.testLevelId = testLevelId;
		this.extReference = extReference;
		this.testcaseRegressionTypeId = testcaseRegressionTypeId;
		this.testcaseExecutions = testcaseExecutions;
		this.testcaseRequirements = testcaseRequirements;
		this.testcaseReleases = testcaseReleases;
		this.testcaseDefects = testcaseDefects;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TESTCASE_WORKSTATE_ID")
	public QTestcaseWorkstate getQTestcaseWorkstate() {
		return this.QTestcaseWorkstate;
	}

	public void setQTestcaseWorkstate(QTestcaseWorkstate QTestcaseWorkstate) {
		this.QTestcaseWorkstate = QTestcaseWorkstate;
	}

	@Column(name = "NAME", nullable = false, length = 2000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "IS_BUSINESS_TESTCASE", precision = 22, scale = 0)
	public BigDecimal getIsBusinessTestcase() {
		return this.isBusinessTestcase;
	}

	public void setIsBusinessTestcase(BigDecimal isBusinessTestcase) {
		this.isBusinessTestcase = isBusinessTestcase;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TESTCASE_AUTOMATION_ID", precision = 38, scale = 0)
	public BigDecimal getTestcaseAutomationId() {
		return this.testcaseAutomationId;
	}

	public void setTestcaseAutomationId(BigDecimal testcaseAutomationId) {
		this.testcaseAutomationId = testcaseAutomationId;
	}

	@Column(name = "TESTCASE_TYPE_ID", precision = 38, scale = 0)
	public BigDecimal getTestcaseTypeId() {
		return this.testcaseTypeId;
	}

	public void setTestcaseTypeId(BigDecimal testcaseTypeId) {
		this.testcaseTypeId = testcaseTypeId;
	}

	@Column(name = "PARENT_ID", precision = 38, scale = 0)
	public BigDecimal getParentId() {
		return this.parentId;
	}

	public void setParentId(BigDecimal parentId) {
		this.parentId = parentId;
	}

	@Column(name = "SOURCE_ORDER", length = 1020)
	public String getSourceOrder() {
		return this.sourceOrder;
	}

	public void setSourceOrder(String sourceOrder) {
		this.sourceOrder = sourceOrder;
	}

	@Column(name = "TESTCASE_PRIORITY_ID", precision = 38, scale = 0)
	public BigDecimal getTestcasePriorityId() {
		return this.testcasePriorityId;
	}

	public void setTestcasePriorityId(BigDecimal testcasePriorityId) {
		this.testcasePriorityId = testcasePriorityId;
	}

	@Column(name = "URL", length = 4000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "CUSTOM1", length = 4000)
	public String getCustom1() {
		return this.custom1;
	}

	public void setCustom1(String custom1) {
		this.custom1 = custom1;
	}

	@Column(name = "CUSTOM2", length = 4000)
	public String getCustom2() {
		return this.custom2;
	}

	public void setCustom2(String custom2) {
		this.custom2 = custom2;
	}

	@Column(name = "CUSTOM3", length = 4000)
	public String getCustom3() {
		return this.custom3;
	}

	public void setCustom3(String custom3) {
		this.custom3 = custom3;
	}

	@Column(name = "CUSTOM4", length = 4000)
	public String getCustom4() {
		return this.custom4;
	}

	public void setCustom4(String custom4) {
		this.custom4 = custom4;
	}

	@Column(name = "EXTERNAL_ENTITY_ID", length = 1020)
	public String getExternalEntityId() {
		return this.externalEntityId;
	}

	public void setExternalEntityId(String externalEntityId) {
		this.externalEntityId = externalEntityId;
	}

	@Column(name = "TEST_STEPS_COUNT", precision = 22, scale = 0)
	public BigDecimal getTestStepsCount() {
		return this.testStepsCount;
	}

	public void setTestStepsCount(BigDecimal testStepsCount) {
		this.testStepsCount = testStepsCount;
	}

	@Column(name = "TARGET_ENTITY_ID", length = 200)
	public String getTargetEntityId() {
		return this.targetEntityId;
	}

	public void setTargetEntityId(String targetEntityId) {
		this.targetEntityId = targetEntityId;
	}

	@Column(name = "CUSTOM5", length = 4000)
	public String getCustom5() {
		return this.custom5;
	}

	public void setCustom5(String custom5) {
		this.custom5 = custom5;
	}

	@Column(name = "CUSTOM6", length = 4000)
	public String getCustom6() {
		return this.custom6;
	}

	public void setCustom6(String custom6) {
		this.custom6 = custom6;
	}

	@Column(name = "CUSTOM7", length = 4000)
	public String getCustom7() {
		return this.custom7;
	}

	public void setCustom7(String custom7) {
		this.custom7 = custom7;
	}

	@Column(name = "CUSTOM8", length = 4000)
	public String getCustom8() {
		return this.custom8;
	}

	public void setCustom8(String custom8) {
		this.custom8 = custom8;
	}

	@Column(name = "CUSTOM9", length = 4000)
	public String getCustom9() {
		return this.custom9;
	}

	public void setCustom9(String custom9) {
		this.custom9 = custom9;
	}

	@Column(name = "CUSTOM10", length = 4000)
	public String getCustom10() {
		return this.custom10;
	}

	public void setCustom10(String custom10) {
		this.custom10 = custom10;
	}

	@Column(name = "IS_REGRESSION_BASIC", precision = 22, scale = 0)
	public BigDecimal getIsRegressionBasic() {
		return this.isRegressionBasic;
	}

	public void setIsRegressionBasic(BigDecimal isRegressionBasic) {
		this.isRegressionBasic = isRegressionBasic;
	}

	@Column(name = "TEST_LEVEL_ID", precision = 38, scale = 0)
	public BigDecimal getTestLevelId() {
		return this.testLevelId;
	}

	public void setTestLevelId(BigDecimal testLevelId) {
		this.testLevelId = testLevelId;
	}

	@Column(name = "EXT_REFERENCE", length = 1020)
	public String getExtReference() {
		return this.extReference;
	}

	public void setExtReference(String extReference) {
		this.extReference = extReference;
	}

	@Column(name = "TESTCASE_REGRESSION_TYPE_ID", precision = 22, scale = 0)
	public BigDecimal getTestcaseRegressionTypeId() {
		return this.testcaseRegressionTypeId;
	}

	public void setTestcaseRegressionTypeId(BigDecimal testcaseRegressionTypeId) {
		this.testcaseRegressionTypeId = testcaseRegressionTypeId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testcase")
	public Set getTestcaseExecutions() {
		return this.testcaseExecutions;
	}

	public void setTestcaseExecutions(Set testcaseExecutions) {
		this.testcaseExecutions = testcaseExecutions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testcase")
	public Set getTestcaseRequirements() {
		return this.testcaseRequirements;
	}

	public void setTestcaseRequirements(Set testcaseRequirements) {
		this.testcaseRequirements = testcaseRequirements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testcase")
	public Set getTestcaseReleases() {
		return this.testcaseReleases;
	}

	public void setTestcaseReleases(Set testcaseReleases) {
		this.testcaseReleases = testcaseReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testcase")
	public Set getTestcaseDefects() {
		return this.testcaseDefects;
	}

	public void setTestcaseDefects(Set testcaseDefects) {
		this.testcaseDefects = testcaseDefects;
	}

}
